mysite/common/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = "common"

urlpatterns = [
    path("login/", auth_views.LoginView.as_view(template_name="common/login.html"), name="login"),
    path("logout/", views.logout_view, name="logout"),
    path("signup/", views.signup, name="signup"),
    path("activate/<str:uid64>/<str:token>/", views.activate, name="activate"),
]

mysite/config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.shortcuts import redirect
from dialog import views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("dialog/", include("dialog.urls")),
    path("common/", include("common.urls")),
    path("", views.index),
]

handler404 = "common.views.page_not_found"

handler500 = "common.views.internal_server_error"

mysite/dialog/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views


app_name = "dialog"
urlpatterns = [
    path("", views.index, name="index"),
    # path("answer/<int:question_id>/", name="get_answer"),     # 챗봇 응답을 위한 URL
    path("feedback/", views.feedback_save, name="feedback_save"),               # 피드백 폼 제출 URL
]

mysite/common/models.py
from django.db import models

# Create your models here.

mysite/dialog/models.py
from django.db import models
from django.contrib.auth.models import User

import datetime
from django.utils import timezone


# 사용자 피드백을 받기 위한 db 테이블
class Feedback(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    user_question = models.TextField()                          # 사용자가 한 질문
    model_classification = models.CharField(max_length=255)     # 대분류, 질문 클래스
    model_answer = models.TextField()                           # 모델이 출력한 답변
    user_intended_classification = models.CharField(max_length=255, blank=True, null=True) # 사용자가 원한 질문 분류 (대분류, 질문 클래스)
    user_desired_answer = models.TextField(blank=True, null=True)   # 사용자가 원한 답변 (사용자가 입력)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Feedback from {self.user.username} on {self.created_at}"

mysite/common/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError


class UserForm(UserCreationForm):
    email = forms.EmailField(label="이메일")

    class Meta:
        model = User
        fields = ["username", "password1", "password2", "email"]

    def clean(self):
        cleaned_data = super().clean()

        email = cleaned_data.get("email")

        if email and not (email.endswith("@mail.hongik.ac.kr") or email.endswith("@g.hongik.ac.kr")):
            self.add_error("email", ValidationError("학교 이메일 (@mail.hongik.ac.kr 또는 @g.hongik.ac.kr)을 입력해주세요"))

        return cleaned_data

mysite/dialog/forms.py
from django import forms
from .models import Feedback

class FeedbackForm(forms.ModelForm):
    class Meta:
        model = Feedback
        fields = [
            'user_question',
            'model_classification',
            'model_answer',
            'user_intended_classification',
            'user_desired_answer',
        ]
        widgets = {
            'user_question': forms.Textarea(attrs={'readonly': 'readonly'}),
            'model_classification': forms.TextInput(attrs={'readonly': 'readonly'}),
            'model_answer': forms.Textarea(attrs={'readonly': 'readonly'}),
        }


mysite/common/views.py
from django.contrib.auth import logout, authenticate, login
from django.shortcuts import render, redirect, HttpResponse
from django.contrib.auth.models import User
from django.contrib.auth.hashers import check_password
from django.contrib.auth import get_user_model
from django.contrib import auth
from .forms import UserForm

from django.contrib.sites.shortcuts import get_current_site
from django.template.loader import render_to_string
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.utils.encoding import force_bytes
from django.core.mail import EmailMessage

from .tokens import account_activation_token
from django.utils.encoding import force_bytes, force_str
from django.db.utils import IntegrityError


def logout_view(request):
    logout(request)
    return redirect("common:login")


def signup(request):
    if request.method == "POST":
        form = UserForm(request.POST)

        exUser = User.objects.filter(username=request.POST["username"])

        if exUser and not exUser.is_active:
            exUser.delete()

        if form.is_valid():
            user = User.objects.create_user(username=request.POST["username"], password=request.POST["password1"], email=request.POST["email"])
            user.is_active = False
            user.save()
            current_site = get_current_site(request)
            message = render_to_string(
                "user_activate_email.html",
                {
                    "user": user,
                    "domain": current_site.domain,
                    "uid": urlsafe_base64_encode(force_bytes(user.pk)).encode().decode(),
                    "token": account_activation_token.make_token(user),
                },
            )
            mail_subject = "[Hongpt] 회원가입 인증 메일입니다."
            email = EmailMessage(mail_subject, message, to=[user.email])
            email.send()
            return HttpResponse(
                '<div style="font-size: 40px; width: 100%; height:100%; display:flex; text-align:center; '
                'justify-content: center; align-items: center;">'
                "입력하신 이메일<span>로 인증 링크가 전송되었습니다.</span>"
                "</div>"
            )
    else:
        form = UserForm()
    return render(request, "common/signup.html", {"form": form})


def activate(request, uid64, token):

    uid = force_str(urlsafe_base64_decode(uid64))
    user = User.objects.get(pk=uid)

    if user is not None and account_activation_token.check_token(user, token):
        user.is_active = True
        user.save()
        auth.login(request, user)
        return redirect("/")
    else:
        return HttpResponse("비정상적인 접근입니다.")


def page_not_found(request, exception):
    return render(request, "common/404.html", {})


def internal_server_error(request):
    return render(request, "common/500.html", {})

mysite/dialog/views.py
from django.db.models import F
from django.http import HttpResponseRedirect, JsonResponse
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.views import generic
from django.views.generic import FormView, TemplateView
from django.template import loader
from django import forms
from django.contrib.auth import logout, authenticate, login
from django.shortcuts import redirect, render
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required

import socket, json
import pandas as pd
from utils.intent import predict
from utils.FindAnswer import FindAnswer
from .forms import FeedbackForm
from .models import Feedback


# 챗봇 응답 처리 뷰
@login_required(login_url="common/login")
def index(request):
    return render(request, "dialog/index.html")


# 피드백 저장 뷰
@login_required
def feedback_save(request):
    """
    Save feedback data received from the user
    """
    if request.method == "POST":
        data = json.loads(request.body)

        # 피드백 데이터 수집
        feedback_text = data.get("user_desired_answer", "")  # 사용자가 입력한 피드백
        user_question = data.get("user_question", "")  # 사용자 질문
        response_id = data.get("responseId")  # 응답 ID

        # 사용자 질문을 사용하여 예측 클래스와 답변 가져오기
        best_sim_idx, predicted_sentence, cos_sim= predict(user_question)  # 모델이 예측한 클래스 ID와 질문
        model_answer, buttons, mode = FindAnswer(best_sim_idx)  # 예측 클래스에 대한 답변, 버튼, 모드

        # 새로운 Feedback 객체를 저장
        Feedback.objects.create(
            user_id=request.user.id,
            user_question=user_question,
            user_desired_answer=feedback_text,
            model_classification=predicted_sentence,
            model_answer=model_answer,
        )

        return JsonResponse({"message": "피드백을 주셔서 감사합니다!"})
    else:
        return JsonResponse({"message": "잘못된 요청입니다."}, status=400)

mysite/templates/common/form_errors.html
<!-- 필드 오류와 넌필드 오류를 출력한다 -->
{% if form.errors %}
    <div class="alert alert-danger">
        <!-- 필드 오류 -->
        {% for field in form %}
            {% if field.errors %}
                <div>
                    <strong>{{ field.label }}</strong>
                    {{ field.errors }}
                </div>
            {% endif %}
        {% endfor %}
        <!-- 넌필드 오류 -->
        {% for error in form.non_field_errors %}
            <div>
                <strong>{{ error }}</strong>
            </div>
        {% endfor %}
    </div>
{% endif %}

mysite/templates/common/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Hongik-gpt 로그인</title>
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
</head>
<body>
    <div id="login-container">
        <h1>Hongik-gpt</h1>
        <form method="post" action="{% url 'common:login' %}">
            {% csrf_token %}
            <input type="hidden" name="next" value="{{ next }}">
            {% include "common/form_errors.html" %}
            <div class="input-group">
                <label for="username">사용자ID</label>
                <input type="text" name="username" id="username" value="{{ form.username.value|default_if_none:'' }}">
            </div>
            <div class="input-group">
                <label for="password">비밀번호</label>
                <input type="password" name="password" id="password" value="{{ form.password.value|default_if_none:'' }}">
            </div>
            <button type="submit" class="btn btn-primary">로그인</button>
        </form>
        <button class="btn btn-secondary" onclick="location.href='{% url 'common:signup' %}'">회원가입</button>
    </div>
</body>
</html>

mysite/templates/common/signup.html
{% load static %}
<!DOCTYPE html>
<html lang="ko">

  <head>
    <meta charset="UTF-8">
    <title>회원가입 - Hongik-gpt</title>
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
  </head>

  <body>
    <div id="signup-container">
      <h1>회원가입</h1>
      <form method="post" onsubmit='return check()' action="{% url 'common:signup' %}">
        {% csrf_token %}
        {% include 'common/form_errors.html' %}
        <div class="input-group">
          <label for="username">사용자 이름</label>
          <input type="text" name="username" id="username" value="{{ form.username.value|default_if_none:'' }}">
        </div>
        <div class="input-group">
          <label for="password1">비밀번호</label>
          <input type="password" name="password1" id="password1" value="{{ form.password1.value|default_if_none:'' }}">
        </div>
        <div class="input-group">
          <label for="password2">비밀번호 확인</label>
          <input type="password" name="password2" id="password2" value="{{ form.password2.value|default_if_none:'' }}">
        </div>
        <div class="input-group">
          <label for="email">이메일</label>
          <input type="text" name="email" id="email" placeholder='abc123@mail.hongik.ac.kr' value="{{ form.email.value|default_if_none:'' }}">
        </div>
        <button type="submit" class="btn btn-primary">생성하기</button>
      </form>
    </div>

    <script>
      let isSubmited = false;
      const check = () => {
        if (isSubmited) 
          return false;
        isSubmited = true;
        return true;
      }
    </script>
  </body>

</html>

mysite/templates/dialog/index.html
{% load static %}
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <title>Hongik-gpt</title>
  <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
  <script src="{% static 'header.js' %}"></script>
  <!-- header.js 파일을 불러오기 -->
</head>

  <body>
    <div id="logout-container">
      {% if user.is_authenticated %}
        <div>{{ user.username }}</div>
        <a href="{% url 'common:logout' %}">로그아웃</a>
      {% else %}
        <div>로그인 안되어있음</div>
      {% endif %}
    </div>

    <div id="chat-container">
      <h1>Hongik-gpt</h1>
      <div id="chat-box" class="chat-content">
        <!-- 기본 안내 메시지 -->
        <div class="msg_box receive">
          <span>
            <strong>Bot:</strong>
            안녕하세요! 홍익대학교 챗봇 Hongik-gpt입니다:)
            <br>
            학교에 대해 궁금한 것을 물어보세요!
            <br>
            <div id="buttons" class="buttons">
              <div class="row">
                <div class="button" id="0">학식</div>
                <div class="button" id="1">편의시설</div>
                <div class="button" id="2">연락처</div>
              </div>
              <div class="row">
                <div class="button" id="3">학사일정</div>
                <div class="button" id="4">공지사항</div>
                <div class="button" id="5">날씨<span>☀</span></div>
              </div>
              <div class="row">
                <div class="button" id="6">홍대 기본 상식</div>
                <div class="button" id="7">졸업 요건 조회</div>
                <div class="button" id="8">열람실 현황</div>
              </div>
            </div>

          </span>
        </div>
      </div>

    <div id ="close-button"></div>
    <div id="buttons" class="buttons" style="display:none;">
      <div class="row">
        <div class="button" id="0">학식</div>
        <div class="button" id="1">편의시설</div>
        <div class="button" id="2">연락처</div>
      </div>
      <div class="row">
        <div class="button" id="3">학사일정</div>
        <div class="button" id="4">공지사항</div>
        <div class="button" id="5">날씨<span>☀</span></div>
      </div>
      <div class="row">
        <div class="button" id="6">홍대 기본 상식</div>
        <div class="button" id="7">졸업 요건 조회</div>
        <div class="button" id="8">열람실 현황</div>
      </div>
    </div>

    <input type="text" id="question" class="chat_input" placeholder="Ask a question">
    <input type="button" id="ask-button" class="send_btn" value="Ask">
  </div>

  <!-- 모달 창 -->
  <div id="feedback-modal" class="modal">
    <div class="modal-content">
      <span class="close" onclick="closeFeedbackModal()">&times;</span>
      <h2>서비스 개선을 위해 피드백을 입력해주세요! 예상한 답변이 무엇이였나요??</h2>
      <form id="feedback-form">
        <textarea id="feedback-text" placeholder="피드백을 입력하세요..."></textarea>
        <button type="submit">제출</button>
      </form>
    </div>
  </div>

  <script src="{% static 'bot.js' %}"></script>
</body>

</html>

mysite/templates/user_activate_email.html
{% autoescape off %}
  안녕하세요 아래 링크를 클릭하면 회원가입 인증이 완료됩니다. 회원가입 링크 : http://{{ domain }}{% url 'common:activate' uid64=uid token=token %}

{% endautoescape %}